# Generated by Django 5.0.4 on 2024-07-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_room_owner_room_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='booking_room',
            new_name='room_id',
        ),
    ]
